INSERT INTO products (name, price, url) VALUES ('Sekiro: Shadows Die Twice', 57.19, 'images/0.jpg');
INSERT INTO products (name, price, url) VALUES ('Root Letter', 9.94, 'images/1.jpg');
INSERT INTO products (name, price, url) VALUES ('Anathema', 100.00, 'images/2.jpg');
INSERT INTO products (name, price, url) VALUES ('Resident Evil 2 Remake', 44.45, 'images/3.jpg');
INSERT INTO products (name, price, url) VALUES ('Farming Simulator 19', 36.44, 'images/4.jpg');
INSERT INTO products (name, price, url) VALUES ('Omega Labyrinth Z', 49.99, 'images/5.jpg');
INSERT INTO products (name, price, url) VALUES ('RAGE 2', 50.17, 'images/6.jpg');
INSERT INTO products (name, price, url) VALUES ('The Caligula Effect: Overdose', 45.99, 'images/7.jpg');
INSERT INTO products (name, price, url) VALUES ('Fortnite : Pack froid éternel', 24.50, 'images/8.jpg');
INSERT INTO products (name, price, url) VALUES ('Whisper: Libres comme le vent', 24.90, 'images/9.jpg');
INSERT INTO products (name, price, url) VALUES ('Wolfenstein Cyberpilot PS4 VR', 24.99, 'images/10.jpg');
INSERT INTO products (name, price, url) VALUES ('Tales of Vesperia: Definitive Edition', 29.99, 'images/11.jpg');
INSERT INTO products (name, price, url) VALUES ("Sid Meier's Civilization VI - Nintendo Switch Edition:, 34.99, 'images/12.jpg');
INSERT INTO products (name, price, url) VALUES ('Taiko No Tatsujin : Drum & Fun pour Nintendo Switch', 49.99, 'images/13.jpg');
INSERT INTO products (name, price, url) VALUES ('Song of Memories', 37.58, 'images/14.jpg');
INSERT INTO products (name, price, url) VALUES ('Persona 5: Dancing in Starlight', 44.45, 'images/15.jpg');
INSERT INTO products (name, price, url) VALUES ('SNK 40th Anniversary Collection', 31.86, 'images/16.jpg');
INSERT INTO products (name, price, url) VALUES ('Fortnite : Pack froid éternel', 24.50, 'images/17.jpg');
INSERT INTO products (name, price, url) VALUES ('Football Manager 2019', 37.74, 'images/18.jpg');
INSERT INTO products (name, price, url) VALUES ('Atari Flashback Classics Volume 3', 7.95, 'images/19.jpg');
INSERT INTO products (name, price, url) VALUES ('Doom Eternal', 50.17, 'images/20.jpg');
INSERT INTO products (name, price, url) VALUES ('Shenmue III', 59.95, 'images/21.jpg');
INSERT INTO products (name, price, url) VALUES ('Pokémon Let's Go Pikachu', 44.99, 'images/22.jpg');
INSERT INTO products (name, price, url) VALUES ('Football Manager 2019', 36.94, 'images/23.jpg');
INSERT INTO products (name, price, url) VALUES ('NBA 2K Playgrounds 2', 22.71, 'images/24.jpg');
INSERT INTO products (name, price, url) VALUES ('Wolfenstein Youngblood', 45.75, 'images/25.jpg');
INSERT INTO products (name, price, url) VALUES ('Team Sonic Racing', 30.72, 'images/26.jpg');
INSERT INTO products (name, price, url) VALUES ('Need For Speed', 19.99, 'images/27.jpg');
INSERT INTO products (name, price, url) VALUES ('Football Manager Touch 2019', 22.06, 'images/28.jpg');
INSERT INTO products (name, price, url) VALUES ('Super Smash Bros Ultimate', 51.99, 'images/29.jpg');
INSERT INTO products (name, price, url) VALUES ('Persona 3: Dancing in Moonlight', 44.45, 'images/30.jpg');
INSERT INTO products (name, price, url) VALUES ('Hello Neighbor : Hide And Seek', 28.43, 'images/31.jpg');
INSERT INTO products (name, price, url) VALUES ('FALLOUT 76', 49.99, 'images/32.jpg');
INSERT INTO products (name, price, url) VALUES ("My Hero: One's Justice", 43.31, 'images/33.jpg');
INSERT INTO products (name, price, url) VALUES ('Yo', 36.99, 'images/34.jpg');
INSERT INTO products (name, price, url) VALUES ('Xenon Racer pour PS4', 49.99, 'images/35.jpg');
INSERT INTO products (name, price, url) VALUES ('Dakar 18', 36.44, 'images/36.jpg');
INSERT INTO products (name, price, url) VALUES ('Hitman 2', 45.99, 'images/37.jpg');
INSERT INTO products (name, price, url) VALUES ('Hasbro Game Night pour Nintendo Switch', 47.88, 'images/38.jpg');
INSERT INTO products (name, price, url) VALUES ('We Happy Few - Season Pass', 19.67, 'images/39.jpg');
INSERT INTO products (name, price, url) VALUES ('Xenon Racer pour Nintendo Switch', 49.99, 'images/40.jpg');
INSERT INTO products (name, price, url) VALUES ('BlazBlue Cross Tag Battle', 20.42, 'images/41.jpg');
INSERT INTO products (name, price, url) VALUES ('Pilot Sports pour Nintendo Switch', 34.99, 'images/42.jpg');
INSERT INTO products (name, price, url) VALUES ('Project Hospital', 22.27, 'images/43.jpg');
INSERT INTO products (name, price, url) VALUES ('Just Cause 4', 45.59, 'images/44.jpg');
INSERT INTO products (name, price, url) VALUES ('Xenon Racer pour Xbox One', 49.99, 'images/45.jpg');
INSERT INTO products (name, price, url) VALUES ('God Wars: The Complete Legend', 37.16, 'images/46.jpg');
INSERT INTO products (name, price, url) VALUES ('11', 28.98, 'images/47.jpg');
INSERT INTO products (name, price, url) VALUES ('Let's Sing 2019: Hits Français et Internationaux', 29.99, 'images/48.jpg');
INSERT INTO products (name, price, url) VALUES ("Hellblade: Senua's Sacrifice", 29.99, 'images/49.jpg');
INSERT INTO products (name, price, url) VALUES ('Senran Kagura Burst Re:Newal', 39.99, 'images/50.jpg');
INSERT INTO products (name, price, url) VALUES ('Dynasty Warriors 9', 21.57, 'images/51.jpg');
INSERT INTO products (name, price, url) VALUES ('Pilot Sports pour PS4', 19.00, 'images/52.jpg');
INSERT INTO products (name, price, url) VALUES ('Nickelodeon Kart Racers', 28.43, 'images/53.jpg');
INSERT INTO products (name, price, url) VALUES ('Persona Dancing: Endless Collection', 99.99, 'images/54.jpg');
INSERT INTO products (name, price, url) VALUES ('Anthem', 59.99, 'images/55.jpg');
INSERT INTO products (name, price, url) VALUES ('NHL 19', 54.99, 'images/56.jpg');
INSERT INTO products (name, price, url) VALUES ('One Piece Pirate Warriors 3 Playstation Hits', 17.99, 'images/57.jpg');
INSERT INTO products (name, price, url) VALUES ('Red Dead Redemption 2', 49.90, 'images/58.jpg');
INSERT INTO products (name, price, url) VALUES ('Youtubers Life pour Xbox One', 29.99, 'images/59.jpg');
INSERT INTO products (name, price, url) VALUES ('Trials Rising', 80.08, 'images/60.jpg');
INSERT INTO products (name, price, url) VALUES ('Disgaea 1 Complete', 49.94, 'images/61.jpg');
INSERT INTO products (name, price, url) VALUES ('11', 28.98, 'images/62.jpg');
INSERT INTO products (name, price, url) VALUES ('Yomawari: The Long Night Collection', 30.99, 'images/63.jpg');
INSERT INTO products (name, price, url) VALUES ('Youtubers Life pour PS4', 29.99, 'images/64.jpg');
INSERT INTO products (name, price, url) VALUES ('Valkyria Chronicles 4', 44.45, 'images/65.jpg');
INSERT INTO products (name, price, url) VALUES ('Ride 3', 44.99, 'images/66.jpg');
INSERT INTO products (name, price, url) VALUES ('Just Dance 2019', 29.74, 'images/67.jpg');
INSERT INTO products (name, price, url) VALUES ('Crayola Scoot', 31.86, 'images/68.jpg');
INSERT INTO products (name, price, url) VALUES ('Jagged Alliance Rage pour PC', 15.85, 'images/69.jpg');
INSERT INTO products (name, price, url) VALUES ('GRIP : Combat Racing', 29.58, 'images/70.jpg');
INSERT INTO products (name, price, url) VALUES ('Battlefield V', 54.95, 'images/71.jpg');
INSERT INTO products (name, price, url) VALUES ('Astérix & Obélix XXL2 Mission: Las Vegum', 29.99, 'images/72.jpg');
INSERT INTO products (name, price, url) VALUES ('American Truck Simulator DLC Oregon', 9.14, 'images/73.jpg');
INSERT INTO products (name, price, url) VALUES ('Warriors Orochi 4', 40.03, 'images/74.jpg');
